Algoritmo "At 21"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/12/2021
Var
x, y:inteiro


Inicio
Escreva(" Digite um numero: ")
leia(x)
Escreva("Digite mais um numero: ")
leia(y)
enquanto (x +  y <= 14) faca
         Escreva(" Digite um numero: ")
         leia(x)
         Escreva("Digite mais um numero: ")
         leia(y)
fimenquanto

Fimalgoritmo